steps:
# Dockerfileを利用してアプリのテストビルドとイメージのビルドを行う。$_VERSIONはトリガーの変数として設定します。
# $PROJECT_IDには使用中のプロジェクトIDが自動的に挿入されます
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cb-sample-server:$_VERSION', '.']
# 作成したcb-sample-serverイメージをPUSHする
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/cb-sample-server:$_VERSION"]
# Clusterを取得。$_ZONEはトリガーの変数として設定します。
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - container
  - clusters
  - get-credentials
  - cb-sample-server
  - --zone=$_ZONE
  - --project=$PROJECT_ID
# アプリのデプロイ設定
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'kubectl'
  args:
    - 'apply'
    - '--filename=deployment.yaml'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_ZONE'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cb-sample-server'

timeout: 1000s
