steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/rikuto-altx/Cloud-build.git']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/dep-counter-cloud/my-app:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dep-counter-cloud/my-app:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '-f'
  - 'deployment.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cloudbuildtest'
images:
- 'gcr.io/dep-counter-cloud/your-image:latest'