apiVersion: apps/v1
kind: Deployment
metadata:
  name: deep-conter-cloud-test
  labels:
    app: deep-conter-cloud-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deep-conter-cloud-test
  template:
    metadata:
      labels:
        app: deep-conter-cloud-test
    spec:
      containers:
      - name: deep-conter-cloud-test-container
        image: gcr.io/dep-counter-cloud/my-app:latest
        ports:
        - containerPort: 80