apiVersion: apps/v1
kind: Deployment
metadata:
  name: cb-sample-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cb-sample-server
  template:
    metadata:
      labels:
        app: cb-sample-server
    spec:
      containers:
      - name: my-container
        image: gcr.io/YOUR_PROJECT_ID/cb-sample-server:latest
        tty: true
        stdin: true
        ports:
        - containerPort: 80